config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :users

  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "unlike", to: "posts#downvote"
    end
    collection do
      get 'search'
    end
    resources :comments, except: [:show]
  end

  match 'users/show', to: 'users#show', via: 'get'
  match 'comments', to: 'comments#index', via: 'get'
  match '/liked', to: 'posts#liked', via: 'get'

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	default_scope -> {order('created_at DESC')}
	validates :body, presence: true, length: {minimum: 2, maximum: 200}
	validates :user_id, presence: true
	validates :post_id, presence: true

	self.per_page = 20
end

app/models/post.rb
class Post < ActiveRecord::Base
	if Rails.env.development?
		has_attached_file :image, :styles => { :medium => "500x", :large => "1000x" }, :default_url => "default.jpg"
		validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] } 
	else
		has_attached_file :image, :styles => { :medium => "500x", :large => "1000x" }, :default_url => "default.jpg",
			:storage => :dropbox,
			:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
			:path => ":style/:id_:filename"
		validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	end

	searchkick

	default_scope -> {order('created_at DESC')}
	validates :content, presence: true, length: {maximum: 200}
	validates :tag, length: {maximum: 100}
	validates_attachment_presence :image

	belongs_to :user
	has_many :comments, dependent: :destroy
	acts_as_votable

	self.per_page = 10

	def score
		self.get_upvotes.size - self.get_downvotes.size
	end
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  acts_as_voter
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post
  before_action :check_user, except: [:index, :create]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @comments = @post.comments.paginate(page: params[:page])
    respond_with(@comments)
  end

  def show 
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = @post.id
    @comment.user_id = current_user.id
    @comment.save
    redirect_to @post
  end

  def update
    @comment.update(comment_params)
    respond_with(@post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_comments_path(@post)
  end

  private

    def check_user
      unless @post.user == current_user || current_user.try(:admin?)
        redirect_to root_url, alert: "You are not authorized."
      end
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'will_paginate/array'
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:liked, :upvote, :downvote, :new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  respond_to :html

  def search
    if params[:search].present?
      @posts = Post.search(params[:search])
    else
      @posts = Post.all
    end
  end

  def liked
    @posts = current_user.find_liked_items.paginate(page: params[:page], per_page: 10)
  end

  def upvote
    @post = Post.find(params[:id])
    @post.liked_by current_user

    respond_to do |format|
      format.js
    end
  end

  def downvote
    @post = Post.find(params[:id])
    @post.unliked_by current_user
    
    respond_to do |format|
      format.js
    end
  end

  def index
    @posts = Post.paginate(page: params[:page])
  end

  def show
    @comments = @post.comments.limit(3)
    @all = @post.comments.all
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    flash.keep[:notice] = "Your post has been created."
    redirect_to root_url 
  end

  def update
    @post.update(post_params)
    flash.keep[:notice] = "Your post has been updated."
    respond_with @post
  end

  def destroy
    @post.destroy
    flash.keep[:alert] = "Post destroyed."
    redirect_to(root_url)
  end

  private

  def check_user
    unless (@post.user == current_user) || (current_user.admin?)
      flash.keep[:alert] = "You are not authorized."
      redirect_to root_url
    end
  end
  
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :image, :tag)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user

def show
	@posts = @user.posts.paginate(page: params[:page])
end

private

def check_user
   unless (@user == current_user) || (current_user.admin?)
   redirect_to root_url, alert: "You are not authorized"
 end
end

def set_user
	@user = User.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<div class="comments">

<% unless @comments.blank? %>

<% @comments.each do |comment| %>

<p><strong><%= link_to comment.user.name, comment.user %>&nbsp;said:</strong>
&nbsp;<%= comment.body %></p>

<% if user_signed_in? %>
<% if @post.user == current_user || current_user.admin? %>

<%= link_to 'delete', [comment.post, comment], method: :delete %></p>

<% end %>
<% end %>

<% end %>

<%= link_to "View All #{@all.count} Comments >>", post_comments_path(@post) %> 

<% else %>

No Comments

<% end %>

</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <strong>Comment:</strong><p></p>
    <%= f.text_field :body, class: "form-control", placeholder: "Leave a Comment..." %>
  </div>

  <p class="minus-top"></p>
  
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/create.js.erb
$(".comments").html("<%= escape_javascript(render partial: 'comments/comments') %>");

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<div class="row text-center">
<h3>All Comments</h3>

<p><%= link_to '<< Back to Post', post_path(@post) %></p>

<% if @comments.blank? %>

No Comments

<% else %>

<% @comments.each do |comment| %>

<p><strong><%= link_to comment.user.name, comment.user %> said:</strong>&nbsp;<%= comment.body %></p>

<% if user_signed_in? %>
<% if @post.user == current_user || current_user.admin? %>

<p><%= link_to "delete", [comment.post, comment], method: :delete, data: {confirm: "Are you sure?"} %></p>

<% end %>
<% end %>

<% end %>

<div class="digg_pagination">
	<%= will_paginate @comments %>
</div>

<% end %>

<p><%= render 'comments/form' %></p>

</div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Crumblr", root_url, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li><%= link_to "Create Post", new_post_path %></li>
      <li><%= link_to "View Profile", current_user %></li> 
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li> 
      <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-left">
       <% if user_signed_in? %>
      <li><%= link_to "Liked Posts", liked_path %></li>
      <% end %>
    </ul>

        <%= form_tag search_posts_path, method: :get, class: "navbar-form navbar-left" do %>
          <%= text_field_tag :search, params[:search], class: "form-control search" %><%= submit_tag "Search", name: nil, class: "btn btn-default inline-button" %>
        <% end %>

  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crumblr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

<div class="container">

<%= render 'layouts/nav' %>

<div class="row text-center">
<% if notice %><p class="notice"><%= notice %></p><% end %>
<% if alert %><p class="alert"><%= alert %></p><% end %>
</div>

<p class="top-margin"></p>

<%= yield %>

</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, :html => { :multipart => true }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <strong><p>Image:</p></strong>
    <%= f.file_field :image, class: "form-control" %>
</div>

  <div class="form-group">
    <strong><p>Comment:</p></strong>
    <%= f.text_area :content, class: "form-control" %>
</div>

  <div class="form-group">
    <strong><p>Tags:</p></strong>
    <%= f.text_field :tag, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
</div>
<% end %>

app/views/posts/_list.html.erb
<% @post.votes_for.voters.each do |voter| %>

<strong><%= link_to voter.name, voter %> likes this.</strong><br>

<% end %>

app/views/posts/_vote.html.erb
<% if current_user.voted_for?(@post) %>

<p>
	<%= link_to image_tag("https://dl.dropboxusercontent.com/s/6ykowyl42is2851/liked.png"), unlike_post_path(@post), class: "ivote", method: :put, remote: true %>
</p>

<% else %>

<p>
	<%= link_to image_tag("https://dl.dropboxusercontent.com/s/e4brk85yxhju2d1/unliked.png"), like_post_path(@post), class: "ivote", method: :put, remote: true %>
</p>

<% end %>

app/views/posts/downvote.js.erb
$(".score").html("<%= @post.score %>");
$(".vote").html("<%= escape_javascript(render partial: 'vote') %>");

app/views/posts/edit.html.erb
<h3>Editing post</h3>

<%= render 'form' %>

<%= link_to 'Back', @post, class: "btn btn-link" %>

app/views/posts/index.html.erb
<div class="row text-center">
<h3>Latest Posts</h3>

<% @posts.each do |post| %>

    <div class="box">

        <p>Posted by <strong><%= link_to post.user.name, post.user %></strong></p>

        <p><%= link_to (image_tag post.image.url(:medium)), post %></p>

        <p><em>"<%= post.content %>"</em></p>

        <p><%= post.score %>&nbsp;Likes</p>

        <p><%= link_to "#{post.comments.count} Comments >>", post_path(post) %></p>

        <% if user_signed_in? %>
        <% if (post.user == current_user) || (current_user.admin?) %>
        <span>
        <%= link_to 'Edit', edit_post_path(post), class: "btn btn-link" %>
        <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></span></p>
        <% end %>
        <% end %>

        </div>
        <p></p>
    <% end %>

    <div class="digg_pagination">
        <%= will_paginate @posts %>
    </div>

</div>

app/views/posts/liked.html.erb
<div class="row text-center">
<h3>Your Liked Posts</h3>

<% unless @posts.blank? %>

<% @posts.each do |post| %>

    <div class="box">

        <p>Posted by <strong><%= link_to post.user.name, post.user %></strong></p>
        <p><%= link_to (image_tag post.image.url(:medium)), post %></p>

        <p><em>"<%= post.content %>"</em></p>

        <p><%= post.score %>&nbsp;Likes</p>

        <p><%= link_to "#{post.comments.count} Comments >>", post_path(post) %></p>

        <% if user_signed_in? %>
        <% if (post.user == current_user) || (current_user.admin?) %>
        <span>
        <%= link_to 'Edit', edit_post_path(post), class: "btn btn-link" %>
        <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></span></p>
        <% end %>
        <% end %>

    </div>
    <p></p>
    
    <% end %>

     <div class="digg_pagination">
        <%= will_paginate @posts %>
    </div>

     <% else %>

     No Posts

     <% end %>

</div>

app/views/posts/new.html.erb
<h3>New post</h3>

<%= render 'form' %>

<%= link_to 'Back', posts_path, class: "btn btn-link" %>

app/views/posts/search.html.erb
<div class="row text-center">
<h3>Search Results</h3>

<% @posts.each do |post| %>

    <div class="box">

        <p>Posted by <strong><%= link_to post.user.name, post.user %></strong></p>

        <p><%= link_to (image_tag post.image.url(:medium)), post %></p>

        <p><em>"<%= post.content %>"</em></p>

        <p><%= post.score %>&nbsp;Likes</p>

        <p><%= link_to "#{post.comments.count} Comments >>", post_path(post) %></p>

        <% if user_signed_in? %>
        <% if (post.user == current_user) || (current_user.admin?) %>
        <span>
        <%= link_to 'Edit', edit_post_path(post), class: "btn btn-link" %>
        <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></span></p>
        <% end %>
        <% end %>

        </div>
        <p></p>
    <% end %>

    <div class="digg_pagination">
        <%= will_paginate @posts %>
    </div>

</div>

app/views/posts/show.html.erb
<div class="row text-center">

<p>
	<strong>Posted by &nbsp;<%= link_to @post.user.name, @post.user %></strong>
</p>

<p>
	<%= image_tag @post.image.url(:large) %>
</p>

<p>
  <em>"<%= @post.content %>"</em>
</p>

<p>
	<strong>Tags:</strong>
	<% unless @post.tag.blank? %>
		<%= @post.tag %>
	<% end %>
</p>

<p>
	<span class="score"><%= @post.score %></span>&nbsp;Likes
</p>

<div class="vote">

<% if user_signed_in? %>

<%= render 'vote' %>

<% else %>

	<%= link_to image_tag("https://dl.dropboxusercontent.com/s/e4brk85yxhju2d1/unliked.png"), new_user_session_path, class: "ivote", notice: "Please login to vote." %>

<% end %>

</div>

<% if user_signed_in? %>
<% if @post.user == current_user || current_user.admin? %>

<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-link" %> |
<%= link_to 'Delete', @post, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-link" %>

<% end %>
<% end %>

<p>

	<h3>Comments:</h3>

<%= render 'comments/comments' %>

</p>

<p>

<%= render 'comments/form' %>

</p>

</div>

app/views/posts/upvote.js.erb
$(".score").html("<%= @post.score %>");
$(".vote").html("<%= escape_javascript(render partial: 'vote') %>");

app/views/users/show.html.erb
<div class="row text-center">
<h3><%= @user.name %>'s Posts</h3>

<% if @user == current_user %>
	<%= link_to "New Post", new_post_path %><br>
<% end %>

<p></p>

<% @posts.each do |post| %>

	<div class="box">

	<p>Posted <%= time_ago_in_words(post.created_at) %> ago.</p>
	<p><%= link_to (image_tag post.image.url(:medium)), post %></p>

	<p><em>"<%= post.content %>"</em></p>

	<p><%= post.score %>&nbsp;Likes</p>

	<p><%= link_to "#{post.comments.count} Comments >>", post_path(post) %></p>

	<% if user_signed_in? %>
	<% if (@user == current_user) || (current_user.admin?) %>
	<span>
       <%= link_to 'Edit', edit_post_path(post), class: "btn btn-link" %>
       <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></span>
     <% end %>
     <% end %>
   </p>

</div>
<p></p>

<% end %>

	<div class="digg_pagination">
        <%= will_paginate @posts %>
    </div>

</div>